name: dart_app
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  filepicker_windows: ^2.0.2
  path: ^1.8.0
  #telegram bot uchun
  teledart: ^0.3.4
  uuid: ^3.0.6
  #hive no sql
  hive: ^2.2.3


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  hive_generator: any
  build_runner: any
